version: '3.7'

services:
  roach1:
    image: cockroachdb/cockroach:latest
    container_name: roach1
    command: start --join=roach1,roach2,roach3 --cache=25% --max-sql-memory=25% --insecure --listen-addr=roach1:26257 --advertise-addr=roach1:26257
    ports:
      - "26257:26257"   # SQL port
      - "8080:8080"     # Admin UI port
    volumes:
      - roach1-data:/cockroach/cockroach-data
      - ./INIT_fantasy_game_setup.sql:/tmp/INIT_fantasy_game_setup.sql
    networks:
      - roachnet
    hostname: roach1

  roach2:
    image: cockroachdb/cockroach:latest
    container_name: roach2
    command: start --join=roach1,roach2,roach3 --cache=25% --max-sql-memory=25% --insecure --listen-addr=roach2:26257 --advertise-addr=roach2:26257
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - roach2-data:/cockroach/cockroach-data
    networks:
      - roachnet
    hostname: roach2
    depends_on:
      - roach1

  roach3:
    image: cockroachdb/cockroach:latest
    container_name: roach3
    command: start --join=roach1,roach2,roach3 --cache=25% --max-sql-memory=25% --insecure --listen-addr=roach3:26257 --advertise-addr=roach3:26257
    ports:
      - "26259:26257"
      - "8082:8080"
    volumes:
      - roach3-data:/cockroach/cockroach-data
    networks:
      - roachnet
    hostname: roach3
    depends_on:
      - roach1

volumes:
  roach1-data:
  roach2-data:
  roach3-data:

networks:
  roachnet:
    driver: bridge
