CREATE SCHEMA IF NOT EXISTS log;
CREATE SCHEMA IF NOT EXISTS engine_config; 
CREATE SCHEMA IF NOT EXISTS game_management;
CREATE SCHEMA IF NOT EXISTS gameplay;
CREATE SCHEMA IF NOT EXISTS game_user;
CREATE SCHEMA IF NOT EXISTS league;
CREATE SCHEMA IF NOT EXISTS point_calculation;
CREATE SCHEMA IF NOT EXISTS backup;